// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOhoboIZZNB4O-BSVEFUIPnpHb-F3X-A',
    appId: '1:858670215890:web:30f96f77963d84390e330b',
    messagingSenderId: '858670215890',
    projectId: 'message-1f2a4',
    authDomain: 'message-1f2a4.firebaseapp.com',
    storageBucket: 'message-1f2a4.firebasestorage.app',
    measurementId: 'G-KT2NJ5BDGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8BOLNix-F7L5yZvcaGPP8CM4O4Ufa8Cg',
    appId: '1:858670215890:android:58408c0e853edd2b0e330b',
    messagingSenderId: '858670215890',
    projectId: 'message-1f2a4',
    storageBucket: 'message-1f2a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2oYBgzp_QTCum4sCo6snPHitDtq7cpg',
    appId: '1:858670215890:ios:68c9df7a6bc0da850e330b',
    messagingSenderId: '858670215890',
    projectId: 'message-1f2a4',
    storageBucket: 'message-1f2a4.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2oYBgzp_QTCum4sCo6snPHitDtq7cpg',
    appId: '1:858670215890:ios:68c9df7a6bc0da850e330b',
    messagingSenderId: '858670215890',
    projectId: 'message-1f2a4',
    storageBucket: 'message-1f2a4.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbOhoboIZZNB4O-BSVEFUIPnpHb-F3X-A',
    appId: '1:858670215890:web:3a4a137fe08612810e330b',
    messagingSenderId: '858670215890',
    projectId: 'message-1f2a4',
    authDomain: 'message-1f2a4.firebaseapp.com',
    storageBucket: 'message-1f2a4.firebasestorage.app',
    measurementId: 'G-HV9E7R56BP',
  );
}
